# Change these first
owner: ParthaDhar # Your GitHub organization or username, where this repository lives
repo: smtnet-uptime # The name of this repository
user-agent: koj-co

sites:
  - name: SMTNet-Prod
    url: https://smtnet.com
    icon: https://smtnet.com/home/new/img/favicon.ico
  - name: POST to SMTNet-Login
    url: https://smtnet.com/accounts/user/index.cfm
    method: POST
  - name: IPv6 test
    url: smtnet.com
    port: 80
    check: "tcp-ping"
    ipv6: true
    #type: globalping # Use the Globalping platform to run the check
    #location: california # Location to run the check from. Default is "World"

assignees: # Users to assign downtime issues (optional)
  - ParthaDhar


